
services:
  jekyll:
    volumes:
        - '.:/srv/jekyll'
    ports:
        - '4000:4000'
        - '35729:35729'
    image: jekyll/jekyll
    command: jekyll serve --livereload --force_polling
    environment:
      - BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM}
    # environment:
    #   - JEKYLL_ENV=production
    # command: jekyll build